//
// Generated file, do not edit! Created by nedtool 4.6 from CustomPackets.msg.
//

#ifndef _CUSTOMPACKETS_M_H_
#define _CUSTOMPACKETS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>CustomPackets.msg:3</tt> by nedtool.
 * <pre>
 * packet Image
 * {
 *     int uniqueID;
 *     string content;
 * }
 * </pre>
 */
class Image : public ::cPacket
{
  protected:
    int uniqueID_var;
    opp_string content_var;

  private:
    void copy(const Image& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Image&);

  public:
    Image(const char *name=NULL, int kind=0);
    Image(const Image& other);
    virtual ~Image();
    Image& operator=(const Image& other);
    virtual Image *dup() const {return new Image(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getUniqueID() const;
    virtual void setUniqueID(int uniqueID);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
};

inline void doPacking(cCommBuffer *b, Image& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Image& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CUSTOMPACKETS_M_H_

